<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-10-06T16:10:45 IST" name="Suite" finished-at="2022-10-06T16:11:32 IST" duration-ms="47622">
    <groups>
    </groups>
    <test started-at="2022-10-06T16:10:45 IST" name="Test" finished-at="2022-10-06T16:11:32 IST" duration-ms="47622">
      <class name="test.NewTest">
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:test.NewTest@506ae4d4]" started-at="2022-10-06T16:10:45 IST" name="beforeTest" finished-at="2022-10-06T16:11:03 IST" duration-ms="18053" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method signature="f()[pri:0, instance:test.NewTest@506ae4d4]" started-at="2022-10-06T16:11:03 IST" name="f" finished-at="2022-10-06T16:11:05 IST" duration-ms="2115" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:test.NewTest@506ae4d4]" started-at="2022-10-06T16:11:32 IST" name="afterTest" finished-at="2022-10-06T16:11:32 IST" duration-ms="250" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- test.NewTest -->
      <class name="test.NewTest2">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:test.NewTest2@771a660]" started-at="2022-10-06T16:11:05 IST" name="beforeClass" finished-at="2022-10-06T16:11:31 IST" duration-ms="25882" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="f()[pri:0, instance:test.NewTest2@771a660]" started-at="2022-10-06T16:11:31 IST" name="f" finished-at="2022-10-06T16:11:32 IST" duration-ms="943" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Adactin.com - Search Hotel] but found [Adactin.com - Hotel Reservation System]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Adactin.com - Search Hotel] but found [Adactin.com - Hotel Reservation System]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at test.NewTest2.f(NewTest2.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:test.NewTest2@771a660]" started-at="2022-10-06T16:11:32 IST" name="afterClass" finished-at="2022-10-06T16:11:32 IST" duration-ms="284" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- test.NewTest2 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
